### ISSUE TITLE
wrong minimum packet size

### ISSUE THREAD

**Issue by rgauweiler** [Railway-CCS/dissectors#2]
I miss in Wireshark with active rasta filter messages mit the size of exact 43 bytes. Initialization Request for example.
In my opinion this is because of line 215/222 in sci.lua.
Should by >= 45 or >44. (Minimum size 43 + 2 byte message size should be allowed)

**Comment by Mq89** [comment]
Thank yo for raising the issue. I'll have a look at it.

Linking the respective function:

https://github.com/Railway-CCS/dissectors/blob/579d9c563f9a2f912d410b363797d2acc9d92b25/dissectors/sci.lua#L208-L258

**Comment by Mq89** [comment]
Dear @rgauweiler,

I think I'm getting down to the issue you describe.
However, neither RaSTA, SCI-LS nor SCI-P have a packet type "Initialization Request". Can you provide the correct packet type you were referring to or more context?

In 373182d I implemented your suggestion.
Could you provide an example dump to test the solution against before I merge it into the main branch? If you are not able to provide a dump, could you confirm that your issue is indeed fixed?

**Comment by rgauweiler** [comment]
Hello,

the packet "Initialization Request" is a generic one. You found it in Eu.SCI-XX-PDI.97 (Baseline 3). It is used in the start up phase, before SCI-P special events come.
Document “20200624 Interface specification SCI Generic Eu.Doc.93 v2.3 (1.A).pdf”

A dump is attached. See #568
568        09:22:28,606726              172.16.12.146   172.16.6.200      SCI         131        5005 ? 5005 Len=89 Data (Request for sending of status information)

And yes. Should be fixed. My local solution was > 44 instead >= 45, which is the same functionality.

Thank you!
Roland

Von: Markus ***@***.***>
Gesendet: Mittwoch, 19. Oktober 2022 21:15
An: Railway-CCS/dissectors ***@***.***>
Cc: Gauweiler, Roland ***@***.***>; Mention ***@***.***>
Betreff: [EXTERNAL] Re: [Railway-CCS/dissectors] wrong minimum packet size (Issue #2)


Dear @rgauweiler<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frgauweiler&data=05%7C01%7Cr.gauweiler%40hima.com%7C08e97eca09ef4e3cb17408dab2064413%7Cdaa147066b654aecb00190a7bef6399d%7C0%7C0%7C638018037233291662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zx6LodO15n80jUd76Mh9lk6pnJoAw07IjiL4JemJoIQ%3D&reserved=0>,

I think I'm getting down to the issue you describe.
However, neither RaSTA, SCI-LS nor SCI-P have a packet type "Initialization Request". Can you provide the correct packet type you were referring to or more context?

In 373182d<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRailway-CCS%2Fdissectors%2Fcommit%2F373182d4f9bf443be9c3508c925903414aa47490&data=05%7C01%7Cr.gauweiler%40hima.com%7C08e97eca09ef4e3cb17408dab2064413%7Cdaa147066b654aecb00190a7bef6399d%7C0%7C0%7C638018037233291662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dJZ3cKMGCJfkbI35p4DnnXpg8zZw5h94rMA4wLEtzqU%3D&reserved=0> I implemented your suggestion.
Could you provide an example dump to test the solution against before I merge it into the main branch? If you are not able to provide a dump, could you confirm that your issue is indeed fixed?

—
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FRailway-CCS%2Fdissectors%2Fissues%2F2%23issuecomment-1284461067&data=05%7C01%7Cr.gauweiler%40hima.com%7C08e97eca09ef4e3cb17408dab2064413%7Cdaa147066b654aecb00190a7bef6399d%7C0%7C0%7C638018037233291662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HtROxJRM0Y%2FvVsNC88imOMxaB0pXq0w3%2Fgf8tZFx%2FMU%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA2RPWBFFQCBUBYOYWX7KGQTWEBCEPANCNFSM56U2TJBQ&data=05%7C01%7Cr.gauweiler%40hima.com%7C08e97eca09ef4e3cb17408dab2064413%7Cdaa147066b654aecb00190a7bef6399d%7C0%7C0%7C638018037233291662%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TV6Dgb6zkMiPGSzz9rUKdV3lgrORUL5vns59lGe60pc%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Informationspflicht nach Art. 13 und 14 DS-GVO: https://www.hima.com/de/informationen-DSGVO Information obligation according to Art. 13 and 14 DS-GVO: https://www.hima.com/en/information-GDPR

HIMA Paul Hildebrandt GmbH, Albert-Bassermann-Str. 28, 68782 Bruehl bei Mannheim
Gesellschaft mit beschraenkter Haftung, Sitz Bruehl, Deutschland - Registergericht Mannheim HRB 720409
USt-ID: DE 144286400
WEEE-Reg.-Nr.: DE87326515

Geschaeftsfuehrender Gesellschafter: Steffen Philipp, Geschaeftsfuehrer: Joerg de la Motte (Vorsitz), Dr. Michael Loebig

Diese Nachricht und saemtliche Anhaenge sind vertraulich und duerfen nicht an Dritte weitergeleitet oder sonst veroeffentlicht werden, soweit nicht ausdruecklich etwas anderes bestimmt ist. Falls Sie nicht der beabsichtigte Empfaenger sind, bitten wir Sie, mit dem Absender Kontakt aufzunehmen und diese Nachricht und saemtliche Anhaenge von Ihrem System zu loeschen. Auch in diesem Fall sind Sie weder berechtigt, diese Nachricht oder etwaige Anhaenge zu kopieren noch deren Inhalt einem Dritten zugaenglich zu machen.

This message and its attachments are confidential and can contain privileged information which may not be distributed or published, unless expressly stated otherwise. If you are not the intended recipient, please notify us immediately and delete this email and its attachments. If you have received this communication in error, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited.
